name: Create Apk

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "README*.md"
      - "app/src/main/res/**"
      - ".github/**"
  push:
    paths-ignore:
      - "README*.md"
      - "app/src/main/res/**"
      - ".github/**"

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: "gradle"
      - name: Build APK
        run: bash ./gradlew assembleReleaseGithub --stacktrace
      - name: List APK outputs
        run: ls -R app/build/outputs/apk || true

      - name: Create GitHub Release and upload APK
        uses: ncipollo/release-action@v1
        with:
          tag: release-${{ github.run_id }}-${{ github.run_attempt }}
          name: Release ${{ github.run_id }}.${{ github.run_attempt }}
          files: app/build/outputs/apk/**/*.apk
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: app/build/outputs/apk/releaseGithub/
